### ISSUE TITLE
Some help text won't display on a white background.

### ISSUE THREAD

**Issue by pmichaud** [hkdb/cpdf#1]
When I attempt to get help information, some of the important text doesn't appear on in my terminal window (which uses a white background).  Attached is a screenshot of how it appears on my screen.

![screenshot_20180828_085824](https://user-images.githubusercontent.com/41962/44727830-8b199900-aaa0-11e8-811f-d2f63f86f667.png)

It would be nice if the text had some method of emphasis other than assuming a dark colored background.

Thanks for this excellent tool!

Pm

**Comment by hkdb** [comment]
Thanks for your feedback, Patrick! I have thought about this before and haven't decided what's the best way to go about automating this aspect. I would love to hear from someone that has experience on this to chime in on how I should go about it. With that said, as you might already know, the quick workaround specifically to users with white backgrounds is to manually remove the code that specifies white in the Python script which is the following:

```
'\033[1;37m' + 
```
and put in a different color of choice.

**Comment by hkdb** [comment]
Closing due to no response.
