### ISSUE TITLE
error No module named 'pyprind'

### ISSUE THREAD

**Issue by alberto56** [hkdb/cpdf#2]
I'm getting this error when trying to use the module:

```
Traceback (most recent call last):
  File "/bin/cpdf", line 19, in <module>
    import os, datetime, sys, glob, re, subprocess, pyprind, time
ModuleNotFoundError: No module named 'pyprind'

```

**Comment by alberto56** [comment]
See also https://github.com/rasbt/pyprind/issues/45

**Comment by HydeFromT70s** [comment]
The message says you are missing pyprind module. Just install it by 'sudo pip3 install pyprind'.

**Comment by alberto56** [comment]
Thanks @HydeFromT70s I tried this, but if [you take a look at this Dockerfile](https://github.com/dcycle/docker-compresspdf/blob/dev/1/Dockerfile), using pip3 to install pyprind works fine, but running cpdf cannot find it nonetheless.

To reproduce make sure Docker is running, then:

    git clone --single-branch --branch dev/1 https://github.com/dcycle/docker-compresspdf.git
    cd ./docker-compresspdf
    ./test.sh 

You can see the [output of the test here](https://circleci.com/gh/dcycle/docker-compresspdf/8).

Thanks!

**Comment by shijianjian** [comment]
If using other envs like conda, you may change the file header from ```#!/bin/user/python3``` to  your own python which shall be found with ```which python```.

**Comment by hkdb** [comment]
It just dawned on me as I decided to play with Gooey today... I have 3.7 and 3.8 installed and pip installs everything to the 3.8 dir but the python3 alias points to 3.7. Could that be what you are experiencing?

My quickest workaround was to put `#!/usr/bin/python38` up top replacing `#/usr/bin/python3`....

**Comment by hkdb** [comment]
Stale. Closing due to lack of response.
